### ISSUE TITLE
Headfone control

### ISSUE THREAD

**Issue by Docbroke** [martinmimigames/little-music-player#16]
Hi, thanks for this wonderful little player.

I have 2 requests to make here,

1. allow play/pause using headfone/bluetooth devices. When I tried to pause using bluetooth button, other app started playing simultaneously.
2. when used from file browser, ithink there is no need to open app page, only notification view shall give better workflow, so that user can change songs from browser without changing apps.

- regards,
sharad

**Comment by wmartinmimi** [comment]
Hi Sharad,

For first point, I agree with you.
Being able to play/pause with hardware buttons would be an expected behaviour for audio players.
The feature will be added in future versions.

For second point, I think it is fixed in newer version. You can try download the app from github release, or from f-droid.
Tell me if I'm wrong.

Thank you for your feedback.

Best regards,
Martinmimi, Maintainer of Martinmimigames

**Comment by Docbroke** [comment]
You are correct indeed. When I checked I had the app open in background so it was brought to foreground on clicking notification to play/pause. But when music is played from browser there is no issue.

**Comment by wmartinmimi** [comment]
I have now added headphone buttons support. (v2.6)
Little bit more information on [the website](https://martinmimigames.github.io/projects/little-music-player/index.html).
F-droid's version may take a while to update.
