### ISSUE TITLE
Would it be possible to add support for internet radios?

### ISSUE THREAD

**Issue by ferlanero** [martinmimigames/little-music-player#26]
[internet_radios.zip](https://github.com/martinmimigames/little-music-player/files/10182939/internet_radios.zip)
I think adding support for streaming internet radios through m3u files would be a great feature for this player.

**Comment by wmartinmimi** [comment]
I think I might add support for local m3u files, and maybe streaming too.
I might create an extra branch as an internet radio only app in the future.
It might take a while to implement though.

Thank you for your idea. :>

**Comment by wmartinmimi** [comment]
Now have partial support for audio streaming. (v2.10)

You can download from Github release, or from website, or from F-droid when they built the app.

You can either share a url to the app, or use a local m3u file as a shortcut.
Currently it only support the first entry in m3u however, all other entries are currently ignored.

The app will auto use a https connection if the internet radio support it and is not self-signed.
A small toast warning will display otherwise.

Better support for m3u files is planned, and is likely to be implemented in the future.
However I will be busy for quite a while, and therefore is unable to implement big stuff in the near future.
Not that anyone should stop sending requests though, I quite like them!

F-droid build may take a while.

**Comment by wmartinmimi** [comment]
Now have better support for stream audio via m3u (v2.11).

The full playlist can be used. You can skip over ones that you want to ignore via the notification.

I cannot connect to some of the streams in your m3u file when testing however, not sure if it is a bug in the app or the server being off.

You can download v2.11 via the following ways:
- [Github](https://github.com/martinmimigames/little-music-player/releases/tag/2.11)
- [Official Website](https://martinmimigames.github.io/projects/little-music-player/index.html)
- F-droid (It may take a while to pull new update however)
