### ISSUE TITLE
Storage permission request is gone on Android 13

### ISSUE THREAD

**Issue by asadise** [martinmimigames/little-music-player#32]
Thanks for Little Music Player App!
Playing m3u/m3u8 was fine on android 12 (with giving storage permission), but after upgrading to android 13, this permission request is gone! here is the [screenshot](https://github.com/martinmimigames/little-music-player/assets/21277743/c771e72e-6db3-430a-963d-b76a5345e191).

**Comment by wmartinmimi** [comment]
Interesting! Could be due to new permission permission required.

I will try fix it when I get the time. :>

**Comment by wmartinmimi** [comment]
Now fixed in v2.12.

You can download v2.12 via the following ways:
- [Github](https://github.com/martinmimigames/little-music-player/releases/tag/2.12)
- [Official Website](https://martinmimigames.github.io/projects/little-music-player/index.html)
- F-droid (It may take a while to pull new update however)
